runtime: python37
instance_class: F2
entrypoint: gunicorn -b :$PORT -t 600 -w 2 endpoints.main:app
vpc_access_connector:
  name: "projects/goldengate1/locations/europe-west1/connectors/svac-ew1-ae-gke-1"

automatic_scaling:
  max_concurrent_requests: 2  # default is 8
  max_instances: 10

env_variables:
  PYTHONPATH: ".:lib"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
